export const browserCoreExamples = [
  "aetherbot browser status",
  "aetherbot browser start",
  "aetherbot browser stop",
  "aetherbot browser tabs",
  "aetherbot browser open https://example.com",
  "aetherbot browser focus abcd1234",
  "aetherbot browser close abcd1234",
  "aetherbot browser screenshot",
  "aetherbot browser screenshot --full-page",
  "aetherbot browser screenshot --ref 12",
  "aetherbot browser snapshot",
  "aetherbot browser snapshot --format aria --limit 200",
  "aetherbot browser snapshot --efficient",
  "aetherbot browser snapshot --labels",
];

export const browserActionExamples = [
  "aetherbot browser navigate https://example.com",
  "aetherbot browser resize 1280 720",
  "aetherbot browser click 12 --double",
  'aetherbot browser type 23 "hello" --submit',
  "aetherbot browser press Enter",
  "aetherbot browser hover 44",
  "aetherbot browser drag 10 11",
  "aetherbot browser select 9 OptionA OptionB",
  "aetherbot browser upload /tmp/file.pdf",
  'aetherbot browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "aetherbot browser dialog --accept",
  'aetherbot browser wait --text "Done"',
  "aetherbot browser evaluate --fn '(el) => el.textContent' --ref 7",
  "aetherbot browser console --level error",
  "aetherbot browser pdf",
];
